name: run-unit-tests

on: push 
 
jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
                        
      - name: Setup node 18
        uses: actions/setup-node@v4
        with: 
          node-version: 18
          
      - name: Install node dependencies
        working-directory: ./xtext/editorserver
        run: npm ci
      
      - name: Code linting - Xtext Editor Server
        working-directory: ./xtext/editorserver
        run: npm run lint

      - name: Create lint report - Xtext Editor Server
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
            name: Lint Results - Xtext Editor Server
            path: "xtext/editorserver/reports/lint-results.xml"
            reporter: java-junit
            fail-on-error: true
